# -*- coding: utf-8 -*-
"""cv-app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VCGqk-YD4qsTLaqRHqdheZUVXaroxl82
"""

from flask import Flask, render_template, request, redirect, url_for, Response
from ultralytics import YOLO
import cv2
import os

app = Flask(__name__)

# Paths
UPLOAD_FOLDER = 'static/uploads'
RESULT_FOLDER = 'static/results'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(RESULT_FOLDER, exist_ok=True)

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['RESULT_FOLDER'] = RESULT_FOLDER

# Load YOLOv8 model (use 'yolov8n.pt' for lightweight version)
model = YOLO('yolov8n.pt')

# Global variable for camera
camera = None


@app.route('/')
def index():
    return render_template('index_cv.html')


# ---------- Image Upload Inference ----------
@app.route('/predict', methods=['POST'])
def predict():
    if 'image' not in request.files:
        return redirect(request.url)
    file = request.files['image']
    if file.filename == '':
        return redirect(request.url)

    # Save uploaded image
    filepath = os.path.join(app.config['UPLOAD_FOLDER'], file.filename)
    file.save(filepath)

    # Run YOLO inference
    results = model(filepath)
    annotated_frame = results[0].plot()  # Draw boxes and labels

    # Save result image
    result_img_path = os.path.join(app.config['RESULT_FOLDER'], file.filename)
    cv2.imwrite(result_img_path, annotated_frame)

    return render_template('index_cv.html',
                           uploaded_image=url_for('static', filename='uploads/' + file.filename),
                           result_image=url_for('static', filename='results/' + file.filename))


# ---------- Camera Stream Inference ----------
def gen_frames():
    global camera
    if camera is None:
        camera = cv2.VideoCapture(0)  # open default webcam

    while True:
        success, frame = camera.read()
        if not success:
            break
        else:
            # Run YOLOv8 inference on the frame
            results = model(frame)
            annotated_frame = results[0].plot()

            # Encode frame as JPEG
            ret, buffer = cv2.imencode('.jpg', annotated_frame)
            frame = buffer.tobytes()

            # Yield frame for browser streaming
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


@app.route('/video_feed')
def video_feed():
    return Response(gen_frames(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')


@app.route('/stop_camera')
def stop_camera():
    global camera
    if camera is not None:
        camera.release()
        camera = None
    return redirect(url_for('index_cv'))


if __name__ == "__main__":
    app.run(debug=True)