# -*- coding: utf-8 -*-
"""nlp-app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FN1VhyAU5pgMNsxY2d3y33coWCYfbrDI
"""

from flask import Flask, request, jsonify, render_template
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences
import pickle

app = Flask(__name__)

# Load model and tokenizer
model = load_model("sentiment_rnn_model.h5")
with open('tokenizer.pkl', 'rb') as handle:
    tokenizer = pickle.load(handle)

max_length = 20  # must match training

@app.route('/')
def home():
    return render_template('index.html')  # simple web page with input form

@app.route('/predict', methods=['POST'])
def predict():
    text = request.form['review']
    seq = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(seq, maxlen=max_length, padding='post', truncating='post')
    prediction = model.predict(padded)[0][0]

    sentiment = "Positive 😀" if prediction > 0.5 else "Negative 😞"
    return render_template('index.html', prediction_text=f"Sentiment: {sentiment}")

if __name__ == '__main__':
    app.run(debug=True)