# -*- coding: utf-8 -*-
"""ts-app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TErD0gLih3YzSNl79TunMkN2M6Lhu-kB
"""

from flask import Flask, render_template, request
import numpy as np
import pandas as pd
from tensorflow.keras.models import load_model
import joblib

# Initialize Flask app
app = Flask(__name__)

# Load model and scaler
model = load_model("rul_model.h5")
scaler = joblib.load("scaler.save")

# Define home route
@app.route('/')
def home():
    return render_template('index_ts.html')

# Define prediction route
@app.route('/predict', methods=['POST'])
def predict():
    try:
        # Example: get sensor input values from form
        features = [float(x) for x in request.form.values()]
        input_data = np.array(features).reshape(1, 50, 24)  # (batch, timesteps, features)

        # Normalize data using saved scaler
        input_data = scaler.transform(input_data.reshape(-1, 24)).reshape(1, 50, 24)

        # Predict RUL
        prediction = model.predict(input_data)
        output = round(prediction[0][0], 2)

        return render_template('index_ts.html', prediction_text=f'Predicted RUL: {output} cycles')

    except Exception as e:
        return render_template('index_ts.html', prediction_text=f"Error: {str(e)}")

# Run the app
if __name__ == "__main__":
    app.run(debug=True)